events{};

http{
    upstream server{
        backend backend1:8000;
        backend backend2:8000;
    };
    sevrer {
        listen / 80;
        location{
            proxy_pass http://server;
        }
    }
}